name: CI for code

on:
  push:
    branches:
    - 'main'
    - 'feature/**'
    - 'infra/**'

jobs:
  # Test all TS code by Deno
  denotest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tests

    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno test --allow-read --allow-net


  # Lint all TS code by Deno
  denolint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno lint
