name: CI for code

on:
  push:
    branches:
    - 'main'
    - 'feature/**'
    - 'infra/**'

jobs:
  # Test all TS code by Deno
  denotest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/tests

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Test all modules
      run: deno test --allow-read --allow-net


  # Lint all TS code by Deno
  denolint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Lint all TS files
      run: deno lint
